### PR TITLE
UI & code tweaks

### PR DESCRIPTION
**Pull request by suburbski**
Also fixed subwindow distances in escape -> etrun menus

### CODE REVIEW

**Comment by boutetnico** [comment]
@suburbski can you remove the autodemo related changes from this PR and make a PR for them?
Also I'm wondering about the removal of `tempDemoStart 1` is it not needed?

**Comment by suburbski** [comment]
The `1` in `tempDemoStart 1` has no effect (unless you wanted to create a cmd called "1"), it will trigger the `tempDemoStart` cmd in cg_servercmds.c either ways

**Comment by boutetnico** [comment]
@suburbski the code in `cg_servercmds.c` is not very explicit, but it will behave differently if an argument is provided to `tempDemoStart` because of this check: `if (trap_Argc() > 1) {`.

**Comment by suburbski** [comment]
@boutetnico I thought that default arg is 0, and `tempDemoStart 1` would parse arg 1, but the default is 1, and 2 is parsed

**Pull request merged**
